# Generated by Django 5.1.4 on 2024-12-14 21:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ingredient_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('max_attendees', models.PositiveIntegerField()),
                ('registered_attendees', models.PositiveIntegerField(default=0)),
                ('time_range', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.recipe')),
            ],
        ),
    ]
