# Generated by Django 5.1.4 on 2024-12-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='joined_users',
            field=models.ManyToManyField(blank=True, related_name='joined_events', to='api.user'),
        ),
    ]
